New eslint rules
thefrontside/javascript pull request #19
Opened 2020-10-07 14:01 UTC by pittst3r

## Motivation

Our current eslint config is unopinionated about whitespace and semicolons, and I am. Seeing diffs that add whitespace at the end of lines or the removal of a newline character at the end of a file drives me a little nuts. Just a little bit.

## Approach

- Sort the rules alphabetically
- Add a bunch of auto-fixable rules around whitespace
- Add the semicolon rule
- Add rule disallowing the initialization of variables using the comma syntax (like `let foo = 1, bar = 2;`)

2020-10-07 14:07 UTC, taras requested changes
It would be helpful if you could include 1 or 2 sentence for each rule to explain why you think we should add them.

2020-10-07 14:23 UTC, cowboyd commented
> Add rule disallowing the initialization of variables using the comma syntax (like let foo = 1, bar = 2;)

Agree whole-heartedly, although going to date myself by recalling when this was actually the preferred nodejs style:

```js
var x = 'one'
  , y = 'two'
  , z = 'three';
```

🤣 😆 😭

2020-10-07 14:26 UTC, cowboyd commented
> It would be helpful if you could include 1 or 2 sentence for each rule to explain why you think we should add them.

Maybe even to the README, that way, it's front and center to anybody viewing the GH project.

2020-10-07 14:41 UTC, pittst3r commented
@taras @cowboyd Thanks for looking. I just updated the description to add detail around my reason for each rule. I agree that it would be good to add reasoning to the readme for each rule. I will add that once we agree on these rule additions.

2020-10-07 14:43 UTC, taras approved these changes
👍 thank you for updating the description

2020-10-07 14:46 UTC, cowboyd commented
> No-op functions are fairly common and in my experience this rule does not add value, only annoyance due to needing to put a return or a comment in no-ops.

I'd even add that empty functions are like `0` for functional programming and represent the base-case where the context is absence of computation. You wouldn't want to do math without being allowed to write `0` and instead having to write `(1 - 1)`  everywhere!

2020-10-07 14:51 UTC, pittst3r commented
> Agree whole-heartedly, although going to date myself by recalling when this was actually the preferred nodejs style

There was like a two-day period about 6 years ago when I learned of that way of doing commas in objects and arrays and thought it was awesome. 😆

2020-10-07 19:00 UTC, pittst3r commented
@cowboyd No rush but I'm going to wait to merge until I have your blessing on this as well.

![The Blessing](https://media.giphy.com/media/3o6wrhRBC66TyPXtE4/giphy.gif)

2020-10-07 19:01 UTC, pittst3r commented
Oh just kidding, I don't have write access to this repo. Someone else will need to merge.

2020-10-08 16:53 UTC, chuckcarpenter commented
@pittst3r it's like you don't even work here. 

![](https://media.giphy.com/media/5zoHyCdbtm8feNkIxJ/giphy.gif)

2020-10-08 16:53 UTC, taras commented
@pittst3r try it now

2020-10-08 17:46 UTC, cowboyd approved these changes
I'm in!

2020-10-08 18:40 UTC, merged